[template]
ignore = [
	".git",
	"cargo-generate.toml",
	".sst",
	"node_modules",
	"target",
	".env",
]

[placeholders]
app_name = { prompt = "Enter the name of your AWS app", default = "sst-template", type = "string" }
crate_name = { prompt = "Enter the name of your Rust app", default = "aws_api", type = "string" }
